#!/bin/bash
#
# Script run on the dockerd host to start the E2E Container.
set -xv

function help {
  ( >&2 echo "$1 <e2e_config file> <input_directory> <num_partitions> <num_executors>")
  exit $2
}

function check_config_dir {
  if [ ! -d $1 ] ; then
    ( >&2 echo "ERROR: Configuration Directory $1 does not exist or is not a directory")
    logger -p user.error "ERROR: Configuration Directory $1 does not exist or is not a directory"
    exit 1
  fi
}

function errexit {
   ( >&2 echo "$1")
   logger -p user.error "$1"
   exit 1
}

if [ $# -eq 0 -o "$1" = "-h" -o "$1" = "--help" ]; then
  help $0 0
fi
if [ $# -ne 4 ]; then
  ( >&2 echo "ERROR: incorrect number of parameters")
  help $0 1
fi

UI=" -e LOCAL_USER_ID=$(id -u)"
UN=" -e LOCAL_USER_NAME=$(id -un)"
GI=" -e LOCAL_GROUP_ID=$(id -g)"
GN=" -e LOCAL_GROUP_NAME=$(id -gn)"
unset OCONF
if [ "${CONF}" ] ; then
  CONF=$(readlink -f ${CONF})
  check_config_dir ${CONF}
else
  CONF=$(readlink -f ${HOME}/e2e)
  [ ! -d ${CONF} ] && CONF=$(readlink -f /etc/e2e)
  if [ ! -d ${CONF} -o ! -r ${CONF}] ; then
    ( errexit "ERROR: Configuration Directories \"${HOME}/e2e\" and \"/etc/e2e\" do not exist, are not directories, or are not readable")
  fi
fi
if [ ! -d ${CONF}/hadoop -o ! -r ${CONF}/hadoop ] ; then
  errexit "ERROR: Hadoop Configuration Directory \"${CONF}/hadoop\" does not exist, is not a directory, or is not readable"
fi
if [ ! -d ${CONF}/spark -o ! -r ${CONF}/spark ] ; then
  errexit "ERROR: Spark Configuration Directory \"${CONF}/spark\" does not exist, is not a directory, or is not readable"
fi
if [ ! -f ${CONF}/site_config -o ! -r ${CONF}/site_config ] ; then
  errexit "ERROR: E2E Site Configuration File \"${CONF}/site_config\" does not exist, is not a directory, or is not readable"
fi
if [ ! -f ${1} -o ! -r ${1} ] ; then
  errexit "ERROR: E2E Configuration File \"${1}\" does not exist, is not a file, or is not readable"
fi
e2e_config=$(readlink -f ${1}) # convert to absolute path name
if [ ! -d ${2} -o ! -r ${2} ] ; then
  errexit "ERROR: E2E Input Data Directory \"${2}\" does not exist, is not a directory, or is not readable"
fi
shared_top=$(readlink -f ${2})
if ! [[ ${3} =~ ^[0-9]+$ ]] ; then
  errexit "ERROR: number of partitions value \"${3}\" is not an integer value"
fi
if ! [[ ${4} =~ ^[0-9]+$ ]] ; then
  errexit "ERROR: number of executors value \"${4}\" is not an integer value"
fi

source ${CONF}/site_config
[ "${shared_top}" ] || errexit "ERROR: the \"shared_top\" variable is not defined in the \"${CONF}/shared_config\" file"
if [ ! -d ${shared_top} -o ! -r ${shared_top} ] ; then
  errexit "ERROR: The E2E Shared Directory \"${shared_top}\" does not exist, is not a directory, or is not readable"
fi
shared_top=$(readlink -f ${shared_top})
unset V1 V2 V3 V4 V5 V6 V7 P1
V1=" -v ${CONF}/hadoop:/etc/hadoop/conf.shared"
V2=" -v ${CONF}/spark:/var/lib/spark-2.0.0-hadoop2.6/conf"
V3=" -v ${shared_top}:/sharedData"
V4=" -v $(readlink -f ${1}):/e2e_config"
V5=" -v $(readlink -f ${2}):/input"
V6=" -v ${CONF}/site_config:/var/lib/adept-e2e/etc/site_config"
V7=" -v $(readlink -f ${PWD}):/output"
P1=" -p 4040:4040"
unset E1 E2
[ "${deploymode}" ] && E1="-e deploymode=${deploymode}"
[ "${master}" ] && E2="-e master=${master}"

if [ \( ! "$DOCKER_CERT_PATH" -o ! "$DOCKER_HOST" -o ! "$DOCKER_TLS_VERIFY" \) -a \( $(id -u) -ne 0 \) ] ; then
  SUDO="sudo "
else
  unset SUDO
fi
${SUDO}docker run -it $UI $UN $GI $GN $E1 $E2 $V1 $V2 $V3 $V4 $V5 $V6 $V7 $P1 deft/e2e e2e.sh $3 $4

