#!/bin/bash
# Run as root by run-parts by /entrypoint before a2kd is executed
# temporary script to fix up the Illinois XlWikifier Multilanguage configuration file
set -xv
dirs=$(grep -F spark.executor.extraClassPath /input/spark.conf | cut -f 2 | tr ':' ' ')
for dir in $dirs; do
  [ -e "$dir/xlwikifier-demo.config" ] && xlwcf="$dir/xlwikifier-demo.config" && break;
done
if [ ! -e ${xlwcf:-/notExists} ]; then
  echo "${0}: cannot locate xlwikifier-demo.config in the classpath!!"
  exit 0
fi
if [ ! -r ${xlwcf} ]; then
  echo "xlwikifier-demo.config file ${xlwcf} cannot be read"
  exit 0
fi
cp ${xlwcf} /classes
xlwcf="/classes/xlwikifier-demo.config"
[ -d "${dir}/illinois-wikifier-models" ] || dir="$(dirname "$dir")"
if [ ! -d "${dir}/illinois-wikifier-models" ]; then
  echo "xlwikifier-demo model dir ${dir}/illinois-wikifier-models does not exist"
  exit 0
fi

sed -i "s!\$ext_classpath/!${dir}/!g" ${xlwcf}
sed -i "s!/nfs/mercury-04/u40/e2e_artifacts/!${dir}/!" ${xlwcf}
exit 0
