#!/bin/bash
# Run as root by run-parts by /entrypoint.sh before a2kd is executed
# temporary script to fix up the Serif configuration file

dirs=$(awk '/spark.executor.extraClassPath/ {print $2}' /input/spark.conf | tr ':' ' ')
if [ ! "$dirs" ]; then
  echo "${0}: spark.executor.extraClassPath definition not found in spark configuration"
  exit 0
fi
for dir in $dirs; do
  [ -e "$dir/serif_config.xml" ] && scf="$dir/serif_config.xml" && break;
done
if [ ! -e ${scf:-/notExists} ]; then
  echo "${0}: cannot locate serif_config.xml in the classpath!!"
  exit 0
fi
if [ ! -r ${scf} ]; then
  echo "serif_config.xml file ${scf} cannot be read"
  exit 0
fi
cp ${scf} /classes
nscf="/classes/serif_config.xml"
[ -d "${dir}/com/bbn/serif" ] 
if [ ! -d "${dir}/com/bbn/serif" ]; then
  echo "Serif dir ${dir}/com/bbn/serif does not exist"
  exit 0
fi

sed -i "s!\$ext_classpath/!${dir}/!g" ${scf}
sed -i "s!/nfs/mercury-04/u40/e2e_artifacts/e2e_external_classpath!${dir}/!" ${scf} # just in case
exit 0
