#!/bin/bash
if [ "$1" = version ]; then
  cat /git.properties
  exit 0
fi

trap '[ -r /var/run/supervisord.pid ] && kill -TERM $(cat /var/run/supervisord.pid)' TERM
trap '[ -r /var/run/supervisord.pid ] && kill -QUIT $(cat /var/run/supervisord.pid)' QUIT
trap '[ -r /var/run/supervisord.pid ] && kill -QUIT $(cat /var/run/supervisord.pid)' KILL
trap '[ -r /var/run/supervisord.pid ] && kill -HUP $(cat /var/run/supervisord.pid)' HUP

space=$(stat -f --format="%a" /var/lib/data)
if [ "$space" -lt 1024 ] ; then
  echo "ERROR: virtually out of disk space - $space blocks left in /var/lib/data"
  logger "ERROR: virtually out of disk space - $space blocks left in /var/lib/data"
  exit 1
fi
if [ "$space" -lt 2560 ] ; then
  echo "WARNING: 10 MB or less free space in /var/lib/data - only $space blocks free"
  logger "WARNING: 10 MB or less free space in /var/lib/data - only $space blocks free"
fi
if [ ! -f "/var/lib/data/pgsql/data/PG_VERSION" ]; then
    /postgresql-setup
fi
if [ ! -d "/var/lib/data/parliament/data/" ]; then
    /parliament-setup
fi
sudo -u "$(stat --format="#%u" /var/lib/data)" chmod 755 /var/lib/data
scl enable python27 'supervisord -n -c /supervisord.conf' &
echo Waiting for $!
wait
sleep 15 &
wait
echo Wait complete
